// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/library": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/library";
  };
  "routes/layout.tsx": {
    id: "routes/layout";
    page: "/" | "/library";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/library/index.tsx": {
    id: "routes/library/index";
    page: "/library";
  };
};