import * as cloudflare from '@pulumi/cloudflare';

import { accountId } from '../../bridges/constants';

const NAME = 'aeroclime.com';

const getDomain = (): cloudflare.RegistrarDomain =>
  new cloudflare.RegistrarDomain(NAME, {
    accountId,
    domainName: NAME,
    autoRenew: true,
    locked: true,
    privacy: true,
  });

const domains = {
  result: {
    name: 'aeroclime.com',
    available: false,
    supported_tld: true,
    can_register: false,
    premium_type: 'not_premium',
    permissions: [
      'contact_read',
      'contact_write',
      'domain_renew',
      'domain_transfer_out',
      'nameserver_write',
      'domain_delete',
    ],
    fees: {
      transfer_fee: 10.44,
      redemption_fee: 44,
      registration_fee: 10.44,
      renewal_fee: 10.44,
      currency: 'USD',
    },
    registered_billing_version: 'V3',
    current_registrar: 'Cloudflare',
    registered_at: '2025-07-15T14:10:06.183Z',
    expires_at: '2026-07-15T14:10:06.000Z',
    registry_object_id: '3000675893_DOMAIN_COM-VRSN',
    payment_expires_at: '2026-07-15T14:10:06.000Z',
    last_known_status: 'registrationActive',
    name_servers: ['devin.ns.cloudflare.com', 'marlowe.ns.cloudflare.com'],
    ds_records: [],
    registry_statuses: 'clienttransferprohibited,addperiod',
    pending_transfer: false,
    cloudflare_dns: false,
    cloudflare_registration: true,
    policies: {
      suspension: {
        parked: false,
        parking_reason: null,
        payment_expired: false,
      },
    },
    transfer_conditions: {
      exists: true,
      supported_tld: true,
      not_secure: true,
      not_waiting: false,
      not_started: true,
      not_premium: true,
    },
    created_at: '2025-07-15T14:10:06.000Z',
    created_registrar: 'Cloudflare',
    updated_at: '2025-07-15T14:10:11.000Z',
    updated_registrar: 'Cloudflare',
    previous_registrar: null,
    using_current_registrar_nameservers: false,
    using_previous_registrar_nameservers: false,
    using_updated_registrar_nameservers: false,
    using_created_registrar_nameservers: false,
    landing: {
      eligible: false,
    },
    dns: [],
    auto_renew: true,
    privacy: true,
    whois: {
      raw: "Domain name: AEROCLIME.COM\nRegistry Domain ID: \nRegistrar WHOIS Server: whois.cloudflare.com\nRegistrar URL: https://www.cloudflare.com/\nUpdated Date: 2025-07-15T14:10:06Z\nCreation Date: 2025-07-15T14:10:06Z\nRegistrar Registration Expiration Date: 2026-07-15T14:10:06Z\nRegistrar: Cloudflare, Inc.\nRegistrar IANA ID: 1910\nRegistrar Abuse Contact Email: registrar-abuse@cloudflare.com\nRegistrar Abuse Contact Phone: +1-650-319-8936‬\nDomain Status: ok (https://www.icann.org/epp#ok)\nDomain Status: addperiod (https://www.icann.org/epp#addperiod)\nRegistry Registrant ID: \nRegistrant Zip: 2300\nRegistrant City: COPENHAGEN\nRegistrant Email: KORI.KRISTENSEN@GMAIL.COM\nRegistrant Phone: +45.24672430\nRegistrant State: SJÆLLAND\nRegistrant Address: ØRESTADS BOULEVARD 34A, 7.2\nRegistrant Country: DK\nRegistrant Last Name: KRISTENSEN\nRegistrant First Name: KORI\nRegistrant Organization: \nRegistry Admin ID: \nAdmin Zip: 2300\nAdmin City: COPENHAGEN\nAdmin Email: KORI.KRISTENSEN@GMAIL.COM\nAdmin Phone: +45.24672430\nAdmin State: SJÆLLAND\nAdmin Address: ØRESTADS BOULEVARD 34A, 7.2\nAdmin Country: DK\nAdmin Last Name: KRISTENSEN\nAdmin First Name: KORI\nAdmin Organization: \nRegistry Tech ID: \nTech Zip: 2300\nTech City: COPENHAGEN\nTech Email: KORI.KRISTENSEN@GMAIL.COM\nTech Phone: +45.24672430\nTech State: SJÆLLAND\nTech Address: ØRESTADS BOULEVARD 34A, 7.2\nTech Country: DK\nTech Last Name: KRISTENSEN\nTech First Name: KORI\nTech Organization: \nName Server: DEVIN.NS.CLOUDFLARE.COM\nName Server: MARLOWE.NS.CLOUDFLARE.COM\nDNSSEC: unsigned\nURL of the ICANN WHOIS Data Problem Reporting System: http://wdprs.internic.net/\n>>> Last update of WHOIS database: 2025-07-15T14:10:11Z <<<\n\nThe Data in Cloudflare's WHOIS database is provided by Cloudflare for\ninformation purposes, and to assist persons in obtaining information about or\nrelated to a domain name registration record.  Cloudflare does not guarantee\nits accuracy.  By submitting a WHOIS query, you agree that you will use this Data\nonly for lawful purposes and that, under no circumstances will you use this Data to:\n (1) allow, enable, or otherwise support the transmission of mass unsolicited,\n     commercial advertising or solicitations via e-mail (spam); or\n (2) enable high volume, automated, electronic processes that apply to\n     Cloudflare (or its systems).\nCloudflare reserves the right to modify these terms at any time.\nBy submitting this query, you agree to abide by this policy.",
      privacy: true,
      technical: {
        zip: '2300',
        city: 'Copenhagen',
        email: 'kori.kristensen@gmail.com',
        phone: '+45.24672430',
        state: 'Sjælland',
        address: 'Ørestads Boulevard 34A, 7.2',
        country: 'DK',
        last_name: 'Kristensen',
        first_name: 'Kori',
        organization: '',
        id: 16112670,
        label: null,
        uuid: 'f0b57d617f134e7c962b8745f6213c1a',
        email_verified: true,
        material_changes: ['email', 'organization', 'first_name', 'last_name', 'phone'],
      },
      registrant: {
        zip: '2300',
        city: 'Copenhagen',
        email: 'kori.kristensen@gmail.com',
        phone: '+45.24672430',
        state: 'Sjælland',
        address: 'Ørestads Boulevard 34A, 7.2',
        country: 'DK',
        last_name: 'Kristensen',
        first_name: 'Kori',
        organization: '',
        id: 16112668,
        label: null,
        uuid: 'a7da778c6fea406ca63e3c7d6c262fb9',
        email_verified: true,
        material_changes: ['email', 'organization', 'first_name', 'last_name', 'phone'],
      },
      administrator: {
        zip: '2300',
        city: 'Copenhagen',
        email: 'kori.kristensen@gmail.com',
        phone: '+45.24672430',
        state: 'Sjælland',
        address: 'Ørestads Boulevard 34A, 7.2',
        country: 'DK',
        last_name: 'Kristensen',
        first_name: 'Kori',
        organization: '',
        id: 16112669,
        label: null,
        uuid: 'bc80a1afebd84aada1071934676bc3dc',
        email_verified: true,
        material_changes: ['email', 'organization', 'first_name', 'last_name', 'phone'],
      },
    },
    zone_kv: true,
    relations: [
      {
        type: 'DomainRelation::Registrant',
        person_id: 42301591,
        id: 6242946,
      },
    ],
    registry: 'Verisign',
    registrant_contact: {
      id: 'a7da778c6fea406ca63e3c7d6c262fb9',
      label: null,
      first_name: 'Kori',
      organization: '',
      address: 'Ørestads Boulevard 34A, 7.2',
      city: 'Copenhagen',
      state: 'Sjælland',
      zip: '2300',
      country: 'DK',
      phone: '+45.24672430',
      email: 'kori.kristensen@gmail.com',
      fax: '',
      last_name: 'Kristensen',
      address2: '',
      material_changes: ['email', 'organization', 'first_name', 'last_name', 'phone'],
      email_verified: true,
    },
    administrator_contact: {
      id: 'bc80a1afebd84aada1071934676bc3dc',
      label: null,
      first_name: 'Kori',
      organization: '',
      address: 'Ørestads Boulevard 34A, 7.2',
      city: 'Copenhagen',
      state: 'Sjælland',
      zip: '2300',
      country: 'DK',
      phone: '+45.24672430',
      email: 'kori.kristensen@gmail.com',
      fax: '',
      last_name: 'Kristensen',
      address2: '',
      material_changes: [],
      email_verified: true,
    },
    technical_contact: {
      id: 'f0b57d617f134e7c962b8745f6213c1a',
      label: null,
      first_name: 'Kori',
      organization: '',
      address: 'Ørestads Boulevard 34A, 7.2',
      city: 'Copenhagen',
      state: 'Sjælland',
      zip: '2300',
      country: 'DK',
      phone: '+45.24672430',
      email: 'kori.kristensen@gmail.com',
      fax: '',
      last_name: 'Kristensen',
      address2: '',
      material_changes: [],
      email_verified: true,
    },
    billing_contact: {
      id: '4967c2a2646a4b638cedea5c19033368',
      label: null,
      first_name: 'Kori',
      organization: '',
      address: 'Ørestads Boulevard 34A, 7.2',
      city: 'Copenhagen',
      state: 'Sjælland',
      zip: '2300',
      country: 'DK',
      phone: '+45.24672430',
      email: 'kori.kristensen@gmail.com',
      fax: '',
      last_name: 'Kristensen',
      address2: '',
      material_changes: [],
      email_verified: true,
    },
    material_changes: ['email', 'organization', 'first_name', 'last_name', 'phone'],
    cor_responses_pending: 0,
    cor_locked: false,
    cor_changes: null,
    cor_locked_until: null,
    contacts: {
      registrant: {
        id: 'a7da778c6fea406ca63e3c7d6c262fb9',
        label: null,
        first_name: 'Kori',
        organization: '',
        address: 'Ørestads Boulevard 34A, 7.2',
        city: 'Copenhagen',
        state: 'Sjælland',
        zip: '2300',
        country: 'DK',
        phone: '+45.24672430',
        email: 'kori.kristensen@gmail.com',
        fax: '',
        last_name: 'Kristensen',
        address2: '',
        material_changes: ['email', 'organization', 'first_name', 'last_name', 'phone'],
        email_verified: true,
      },
      technical: {
        id: 'f0b57d617f134e7c962b8745f6213c1a',
        label: null,
        first_name: 'Kori',
        organization: '',
        address: 'Ørestads Boulevard 34A, 7.2',
        city: 'Copenhagen',
        state: 'Sjælland',
        zip: '2300',
        country: 'DK',
        phone: '+45.24672430',
        email: 'kori.kristensen@gmail.com',
        fax: '',
        last_name: 'Kristensen',
        address2: '',
        material_changes: [],
        email_verified: true,
      },
      administrator: {
        id: 'bc80a1afebd84aada1071934676bc3dc',
        label: null,
        first_name: 'Kori',
        organization: '',
        address: 'Ørestads Boulevard 34A, 7.2',
        city: 'Copenhagen',
        state: 'Sjælland',
        zip: '2300',
        country: 'DK',
        phone: '+45.24672430',
        email: 'kori.kristensen@gmail.com',
        fax: '',
        last_name: 'Kristensen',
        address2: '',
        material_changes: [],
        email_verified: true,
      },
      billing: {
        id: '4967c2a2646a4b638cedea5c19033368',
        label: null,
        first_name: 'Kori',
        organization: '',
        address: 'Ørestads Boulevard 34A, 7.2',
        city: 'Copenhagen',
        state: 'Sjælland',
        zip: '2300',
        country: 'DK',
        phone: '+45.24672430',
        email: 'kori.kristensen@gmail.com',
        fax: '',
        last_name: 'Kristensen',
        address2: '',
        material_changes: [],
        email_verified: true,
      },
    },
    email_verified: true,
    tags: [],
    locked: true,
    domain_move: {
      ineligibility_reasons: [],
    },
    actionable_metadata: [],
    contacts_updated_at: '2025-07-15T14:10:11.049Z',
    deletion: {
      is_deletable: true,
      cannot_delete_reasons: [],
      is_refundable: false,
      cannot_refund_reasons: ['Not available'],
    },
  },
  success: true,
  errors: [],
  messages: [],
};

export { getDomain };
